repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies: [rich>=13.0.0, typer>=0.12.5, mido>=1.3.2, pytest>=8.3.3]

  - repo: local
    hooks:
      - id: pytest-unit
        name: pytest (unit tests)
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
